// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kpflompryvmfjskbcklq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtwZmxvbXByeXZtZmpza2Jja2xxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyNTM5ODIsImV4cCI6MjA2NTgyOTk4Mn0.0D75_g-W1H3Jc7aapmOWUe1b2FxtVuFkvnLiNjhVoOk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);